### ISSUE TITLE
custom formatter

### ISSUE THREAD

**Issue by northerndeveloper** [Cosium/git-code-format-maven-plugin#55]
Hello

Can we add our customer formatter into git-code-format-maven-plugin or we have to use google's own formatter?

If we can do it , then could you please tell how to do that ?

Thank you for your helps

Regards

**Comment by reda-alaoui** [comment]
Hi,

Currently, you can only use Google Formatter.
But the code is modular enough to be able to use another formatter. It would "just" have to implement `CodeFormatter` interface.

What formatter did you have in mind? If it is a public and popular one, it could be added directly to the plugin.

If it is a formatter that you want to keep private or custom, the project would have to be modified to pull out `CodeFormatter` into a separate SPI module so that you can implement it and declare its implementation class as a parameter of the maven plugin.

**Comment by northerndeveloper** [comment]
Hello Reda-alaoui 

Thanks for your kind response.

For example, I would like to give 10 indentation instead. of 5. Do you think I can provide it ? 
As you said I want to keep it customer , so I should override methods inside CodeFormatter ? I do not understand how to do that . As I should extend it inside the project ?

**Comment by reda-alaoui** [comment]
If your goal is to customize Google Java Formatter indentation, you can't.
Google Java Format has been especially designed to be not customizable.

From https://github.com/google/google-java-format#using-the-formatter:

>Note: There is no configurability as to the formatter's algorithm for formatting. This is a deliberate design decision to unify our code formatting on a single format.

**Comment by northerndeveloper** [comment]
That means I can skip some validations as adding or removing at configurations but for the indentations it's not possible

**Comment by reda-alaoui** [comment]
Well, maybe another way would be to reformat the Google Java Format output yourself.
You ask GCF to format, you take the output and modify its indentation.

But it looks like a daunting task if you are not a code formatter provider :)

**Comment by northerndeveloper** [comment]
Thank you for response. As a conclusion , I understand that I have to use google-java-formatter's formatter not custom one.

Thank you for your helps

**Comment by reda-alaoui** [comment]
You're welcome ;)
