### ISSUE TITLE
unable to format it at Windows Environment

### ISSUE THREAD

**Issue by northerndeveloper** [Cosium/git-code-format-maven-plugin#59]
**What steps will reproduce the problem?**
1. Tested at windows environment.
2. I put cesium google plugin into the root pom.xml as I did the same thing in the UNIX systems.
3. It was working properly. The problem is it does not work at UNIX environment.

**What is the expected output?**
Expected output is it will be automatically formatted during the git commit - push as it works in the UNIx systems but it does not work.

**What happens instead?**
It does not format. Nothing happens. It directly commit and pushes the file.

**Environment:**
 - OS: [e.g. Windows 10] 
 - Git version: [e.g. 2.17.1]
 - git-code-format-maven-plugin version: [e.g. 2.5]
 - Maven version: [e.g. 3.5.4]

**Link to a git repository that can be cloned to reproduce the problem:**
This is critical. The absence of such repository will greatly reduce the chances of seeing the issue resolved.

**Additional context**

**Comment by northerndeveloper** [comment]
Hello. Do you have any suggestion about the issue ?

**Comment by cmoine** [comment]
I personally do not have this error. Looks like your "precommit" hook is not taken into account. Which git client are you using? I'm using Git Bash.

**Comment by BrianMasiga** [comment]
It seems like the git-code-format-maven-plugin is not working properly in the UNIX environment, while it works in the Windows environment. This could be due to differences in the way the plugin is configured or installed on each system.

To further diagnose the issue, you could try checking the plugin's configuration in the pom.xml file and comparing it between the Windows and UNIX environments. You could also check if there are any errors or warnings related to the plugin in the build logs or console output.

Additionally, you could try reproducing the issue in a sample project or creating a separate repository for testing purposes to isolate the problem. This could help in identifying any specific environmental or configuration issues that might be causing the problem.

**Comment by reda-alaoui** [comment]
@northerndeveloper please open a new issue by respecting the issue template. In addition, the issue title says the opposite of the description. Hard to understand if the issue is occuring on Windows or Unix …
